### ISSUE TITLE
:gear: | Add youtube channels in data

### ISSUE THREAD

**Issue by zclut** [klasinky/karmaland-ui#3]
# Expected Behavior
Add the karmaland members of youtube in the data

# Current Behavior
Only twitch members are here

## Steps to Reproduce
1. Go to `./src/data/`
2. Modify the variable **karmaland** and add the youtube members

**Comment by mehraankush** [comment]
any random name would work or any suggestion of your choice..

**Comment by mehraankush** [comment]
and how many members you want to get add ..
