### ISSUE TITLE
Add English translation | Internationalization

### ISSUE THREAD

**Issue by klasinky** [klasinky/karmaland-ui#5]
# Expected Behavior
Be able to see the website in English, you can use any library

# Current Behavior
It's only in Spanish

## Steps to Reproduce
1. Building a language selector to switch between languages
2. Use arguments in your translated text

### Note

If you want another language, you are welcome to create an issue

**Comment by ArinCodes** [comment]
Assign me This I would Like to work on this issue

**Comment by zclut** [comment]
> Assign me This I would Like to work on this issue

Sure! 👌
